// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCorjVjiY1PbiB8Utx7wHAFBytZmQnzEh0',
    appId: '1:790178730226:web:1ff7c1efca0fbcfdde806b',
    messagingSenderId: '790178730226',
    projectId: 'meitar-code-quiz',
    authDomain: 'meitar-code-quiz.firebaseapp.com',
    storageBucket: 'meitar-code-quiz.firebasestorage.app',
    measurementId: 'G-PFSM3FHW7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP95S4gfY4gCyE1SEGhkICeYeYLaQR56M',
    appId: '1:790178730226:android:bae72163c39c3bc2de806b',
    messagingSenderId: '790178730226',
    projectId: 'meitar-code-quiz',
    storageBucket: 'meitar-code-quiz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPOwPCHOuqQMLmqY6fUXcNWnz_fa18gJE',
    appId: '1:790178730226:ios:3cd790fbce9a173dde806b',
    messagingSenderId: '790178730226',
    projectId: 'meitar-code-quiz',
    storageBucket: 'meitar-code-quiz.firebasestorage.app',
    iosBundleId: 'com.example.codeQuiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPOwPCHOuqQMLmqY6fUXcNWnz_fa18gJE',
    appId: '1:790178730226:ios:3cd790fbce9a173dde806b',
    messagingSenderId: '790178730226',
    projectId: 'meitar-code-quiz',
    storageBucket: 'meitar-code-quiz.firebasestorage.app',
    iosBundleId: 'com.example.codeQuiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCorjVjiY1PbiB8Utx7wHAFBytZmQnzEh0',
    appId: '1:790178730226:web:7437c454976b8b05de806b',
    messagingSenderId: '790178730226',
    projectId: 'meitar-code-quiz',
    authDomain: 'meitar-code-quiz.firebaseapp.com',
    storageBucket: 'meitar-code-quiz.firebasestorage.app',
    measurementId: 'G-J98DN87Q9G',
  );
}
